version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    environment:
      - DATABASE_URI=postgresql://user:password@db/user_service
      - JWT_SECRET_KEY=038f48cacc0793319d521357220b563ff46632d998fcae135eaae566fd71dc3c

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"

  blog-service:
    build: ./blog-service
    environment:
      - DATABASE_URI=postgresql://user:password@db/blog_service
      - JWT_SECRET_KEY=038f48cacc0793319d521357220b563ff46632d998fcae135eaae566fd71dc3c

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5002:5002"

  comment-service:
    build: ./comment-service
    environment:
      - DATABASE_URI=postgresql://user:password@db/comment_service
      - JWT_SECRET_KEY=038f48cacc0793319d521357220b563ff46632d998fcae135eaae566fd71dc3c

    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5003:5003"
